# -*- coding: utf-8 -*-
"""Day-48

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feTV4oHTqAwEQzOnCsiln49yCiO3Oe4B
"""

from transformers import pipeline

def summarize_text(text):
    summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
    summary = summarizer(text, max_length=50, min_length=20, do_sample=False)
    return summary[0]['summary_text']

# Example usage
paragraph = "Artificial Intelligence is a rapidly evolving field that aims to create machines capable of intelligent behavior. It includes various subfields such as machine learning, natural language processing, and computer vision. AI applications are widely used in industries like healthcare, finance, and transportation, making our lives more efficient and productive."

summary = summarize_text(paragraph)
print("Summary:", summary)

