# -*- coding: utf-8 -*-
"""Day-46

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QRFSqZvZurDjqO8JG-u3k-_MKlvK1tUL
"""

def simple_chatbot():
    responses = {
        "hello": "Hi! How can I help you?",
        "how are you?": "I'm just a bot, but I'm doing great! How about you?",
        "bye": "Goodbye! Have a nice day!"
    }

    while True:
        user_input = input("You: ").strip().lower()

        if user_input in responses:
            print(f"Bot: {responses[user_input]}")
            if user_input == "bye":
                break
        else:
            print("Bot: I'm sorry, I don't understand.")

# Run the chatbot
simple_chatbot()

