# -*- coding: utf-8 -*-
"""Day-50

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQFWeQ3hDHOMRv5Qd91_NqsO2DrRs-Mf
"""

import numpy as np

def attention_scores():
    query = np.random.rand(1, 3)
    key = np.random.rand(3, 3)
    value = np.random.rand(3, 3)
    scores = np.dot(query, key.T)
    attention_weights = np.exp(scores) / np.sum(np.exp(scores), axis=1, keepdims=True)
    output = np.dot(attention_weights, value)

    return output
result = attention_scores()
print("Attention Output:\n", result)

